server:
  port: 8080

spring:
  config:
    # .env 를 .env.properties 로 가져옴. optional 이기 때문에 .env 없어도 괜찮음
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
          hibernate:
            show_sql: true
            format_sql: true
            order_updates: true
            order-inserts: true
            jdbc:
              batch_size: 100
            ddl-auth: validate
            dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 3GB
      max-request-size: 3GB
  web:
    resources:
      add-mappings: true
# logging
logging:
  level:
    org:
      springframework:
        jdbc: debug