server:
  port: 8080

spring:
  config:
    # .env 를 .env.properties 로 가져옴. optional 이기 때문에 .env 없어도 괜찮음
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
          hibernate:
            show_sql: true
            format_sql: true
            order_updates: true
            order-inserts: true
            jdbc:
              batch_size: 100
            ddl-auth: validate
            dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 3GB
      max-request-size: 3GB
  web:
    resources:
      add-mappings: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_LOGIN_REST_API_KEY}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-name: kakao
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - account_email
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            client-name: google
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - profile
              - email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub # 사용자 식별 요소로 사용

# logging
logging:
  level:
    org:
      springframework:
        jdbc: debug
