name: CI using github actions & docker

#on:
#  push:
#    branches: ["main"]
on:
  workflow_dispatch: # 수동 실행 전용 트리거

permissions:
  contents: read

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # 환경변수 가져오기(secret 에 .env 로 저장되어 있음)
      - name: Make .env file
        run: echo "${{ secrets.ENV }}" | base64 --decode > .env

      # firebase key 가져오기
      - name: Make firebase-key.json file
      - run : echo "${{ secrets.FIREBASE_KEY }}" | base64 --decode > ./src/main/resources/firebase-key.json

      # 이미지 빌드
      - name: Build image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/bookafe-back .

      # 도커 로그인
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 허브에 push
      - name: push image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/bookafe-back:latest
